apiVersion: v1
kind: ReplicationController
metadata:
  name: test-frontend
spec:
  replicas: 2
  selector:
    app: test-frontend
  template:
    metadata:
      name: test-frontend
      labels:
        app: test-frontend
    spec:
      containers:
      - name: test-frontend
        image: gburanov/pr_helper_frontend
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pr-helper-service
spec:
  ports:
    -
      port: 9376
      targetPort: 3000
  selector:
    app: test-frontend
  type: LoadBalancer
