# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1dc74ca509a4f8993c88ee8a712e314c47e1eff07045e4b13f79c375794afe94bf4040875070477ef7501b2d42fcd56922d4d60952eadd579210728d8f2758a

test:
  secret_key_base: d153a96b5c3333d87ba3bfbd642a0320ca830127e0971dba4a38750f0911d84e3f542356e688b86d472718f96ab0e6d830e6ed59b282f441eb9f6f77539ab695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
